/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef data_model_CONSTANTS_H
#define data_model_CONSTANTS_H

#include "data_model_types.h"



class data_modelConstants {
 public:
  data_modelConstants();

};

extern const data_modelConstants g_data_model_constants;



#endif
