/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "data_model_constants.h"



const data_modelConstants g_data_model_constants;

data_modelConstants::data_modelConstants() {
}



